[package]
name = "add-determinism"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.12"
clap = { version = "4.4.18", features = ["derive"] }
log = { version = "0.4", features = ["std"] }
pyo3 = "0.20.0"
walkdir = "2.5.0"

[dev-dependencies]
tempfile = "3"
ctor = "0.1"
